name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: zulu
      - name: Build with Gradle
        run: xvfb-run --auto-servernum ./gradlew test --info
